### ISSUE TITLE
dot "." command crashed application on Mac OSX.

### ISSUE THREAD

**Issue by jm4l1** [sachinites/CommandParser#6]
When entering the dot "." command at the command line, the application crashes on Mac OSX causing an `Abort trap: 6` .

```run - 'show help' cmd to learn more
root@juniper> $ .
Parse Success.
ROOT show help
Abort trap: 6
```

When building the following warning is received

```
clistd.c:51:13: warning: '__builtin___memset_chk' will always overflow destination buffer [-Wbuiltin-memcpy-chk-size]
            memset(temp, 0, LEAF_VALUE_HOLDER_SIZE + 2);
```
LEAF_VALUE_HOLDER_SIZE is defied as 64 , while `temp` is 32. causing buffer over flow.

Changing to to the below removes the compile error and the error in the application is no longer received.

`memset(temp, 0, sizeof(temp));`

**Comment by sachinites** [comment]
committed the fix. Thanks for pointing out the bug.
